name: Basili.co
favicon: null
layout_spectrum: 0.9823229177854955
typography_spectrum: 0.9851500629447401
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.699449012754485
  lightness: 0.28125210851430893
  saturation: 0.47628113301470876
  rhythmicContrast: 0.0073247975669801235
purpose: []
